### ISSUE TITLE
Version tags and releases

### ISSUE THREAD

**Issue by yurtpage** [vathpela/gnu-efi#18]
Could you please add a git tag for a release version and ideally also create a release on the GitHub
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

This is a common practice and helps a lot for package maintainers.

**Comment by yurtpage** [comment]
And a similar problem here https://github.com/rhboot/efibootmgr

**Comment by ghost** [comment]
How about you fork the repo and do it yourself?
