### ISSUE TITLE
StrHasPrefix string helper

### ISSUE THREAD

**Issue by hughsie** [vathpela/gnu-efi#7]
Would something like `StrHasPrefix()` and `StrHasSuffix` (or `StrStartsWith()` and `StrEndsWith`) be accepted? If so, I'm happy to submit a PR. Thanks.

**Comment by vathpela** [comment]
Sure?

**Comment by hughsie** [comment]
Which is your poison?

**Comment by vathpela** [comment]
StrStartsWith()/StrEndsWith() I guess.  Where are you thinking we'll use it?

**Comment by hughsie** [comment]
>  Where are you thinking we'll use it

The EFI fwupdate helper in fwupd.

**Comment by Ivanhu5866** [comment]
Why not just use CompareMem
https://github.com/fwupd/fwupd/pull/1708
