### ISSUE TITLE
Implement gnu-efi quiet mode

### ISSUE THREAD

**Issue by IniterWorker** [vathpela/gnu-efi#9]
Hello,

I'm looking to modify the gnu-EFI to clear the framebuffer only in error state. I want to keep my splash screen from the BIOS to the User Space without efibootguard clear my frame buffer.

I'm wondering what's the function who touches the framebuffer to remove this interaction.

## Update

After some research, I'm wondering if the framebuffer already cleaned before the "gnu-EFI" is loaded.

Br,

**Comment by vathpela** [comment]
gnu-efi may be /enabling/ whatever code is doing this by providing the protocol it's using or whatnot, but it isn't doing this itself.
